(self.AMP=self.AMP||[]).push({n:"amp-autocomplete",v:"2011252111002",f:(function(AMP,_){
'use strict';var l,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function ba(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}ba(this);"function"===typeof Symbol&&Symbol("x");var m;
if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var ca={a:!0},q={};try{q.__proto__=ca;n=q.a;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var r=m,t;function u(){return t?t:t=Promise.resolve(void 0)};function v(a,b){var c=b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(d){return c}};var da=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;var ea=Object.prototype.toString;function w(a){return Array.isArray(a)};function fa(a){var b=!1,c=null,d=a;return function(e){for(var f=[],g=0;g<arguments.length;++g)f[g-0]=arguments[g];b||(c=d.apply(self,f),b=!0,d=null);return c}};var x=self.AMP_CONFIG||{},ha=("string"==typeof x.cdnProxyRegex?new RegExp(x.cdnProxyRegex):x.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function ia(a){if(!self.document||!self.document.head||self.location&&ha.test(self.location.origin))return null;var b=self.document.head.querySelector('meta[name="'+a+'"]');return b&&b.getAttribute("content")||null}
var ja={thirdParty:x.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:x.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof x.thirdPartyFrameRegex?new RegExp(x.thirdPartyFrameRegex):x.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:x.cdnUrl||ia("runtime-host")||"https://cdn.ampproject.org",cdnProxyRegex:ha,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:x.errorReportingUrl||"https://us-central1-amp-error-reporting.cloudfunctions.net/r",betaErrorReporting:x.betaErrorReportingUrl||
"https://us-central1-amp-error-reporting.cloudfunctions.net/r-beta",localDev:x.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:x.geoApiUrl||ia("amp-geo-api")};self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var y=self.__AMP_LOG;function z(){if(!y.user)throw Error("failed to call initLogConstructor");return y.user}function ka(){}function A(a,b,c,d,e){z().assert(a,b,c,d,e,void 0,void 0,void 0,void 0,void 0,void 0)};var B=Object.prototype.hasOwnProperty;function C(a){return a||{}}function D(a,b){if(B.call(a,b))return a[b]};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function la(a,b){var c;"number"!==typeof c&&(c=0);return c+b.length>a.length?!1:-1!==a.indexOf(b,c)};function ma(a){var b=a.element;this.X=b;this.H=this.X.getAttribute("inline");A(""!==this.H,'Empty value for the "inline" attr is unsupported, %s. %s',"amp-autocomplete",b);A(""!==this.H,"AutocompleteBindingInline does not support an empty value in the constructor.");this.D=null;var c=this.H.replace(/([()[{*+.$^\\|?])/g,"\\$1");this.da=new RegExp("(("+c+"|^"+c+")(\\w+)?)","gm")}l=ma.prototype;
l.shouldAutocomplete=function(a){var b;if(b=this.da){for(var c=a.value,d=a.selectionStart,e,f;null!==(e=b.exec(c))&&!(e[0].length+D(e,"index")>d);)f=e;b=!f||f[0].length+D(f,"index")<d?null:f}else b=null;this.D=b;return!!b};l.getUserInputForUpdate=function(){return this.D&&this.D[0]?this.D[0].slice(this.H.length):""};
l.getUserInputForUpdateWithSelection=function(a,b,c){if(!this.D)return b.value;var d=b.selectionStart,e=Number(D(this.D,"index")),f=c.length;d>=e+f&&(d-=f);try{b.focus()}catch(k){}d=d+a.length+1;b.setSelectionRange(d,d);this.D=null;b=b.value;var g=b.slice(0,e+this.H.length),h=b.slice(e+this.H.length+f);return g+a+" "+h};l.resetInputOnWrapAround=function(){};l.shouldSuggestFirst=function(){return this.X.hasAttribute("suggest-first")};l.shouldShowOnFocus=function(){return!1};
l.displayActiveItemInInput=function(){};l.removeSelectionHighlighting=function(){};l.shouldPreventDefaultOnEnter=function(a){return a};function na(a){a=a.element;this.B=a.hasAttribute("suggest-first");var b=a.getAttribute("filter");this.B&&"prefix"!==b&&(this.B=!1,z().warn("AMP-AUTOCOMPLETE",'"suggest-first" expected "filter" type "prefix".'));this.fa=a.hasAttribute("submit-on-enter")}l=na.prototype;l.shouldAutocomplete=function(){return!0};l.getUserInputForUpdate=function(a){return a.value||""};l.getUserInputForUpdateWithSelection=function(a){return a};l.resetInputOnWrapAround=function(a,b){b.value=a};l.shouldSuggestFirst=function(){return this.B};
l.shouldShowOnFocus=function(){return!0};l.displayActiveItemInInput=function(a,b,c){a.value=b;this.B&&a.setSelectionRange(c.length,b.length)};l.removeSelectionHighlighting=function(a){var b=a.value.length;a.setSelectionRange(b,b)};l.shouldPreventDefaultOnEnter=function(){return!this.fa};function E(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return F(a,b)}function oa(a,b){var c=G(a);c=pa(c);return F(c,b)}function qa(a,b){a=G(a);a=pa(a);return ra(a,b)?F(a,b):null}function G(a){return a.nodeType?E((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function pa(a){a=G(a);return a.isSingleDoc()?a.win:a}
function F(a,b){ra(a,b);var c=a.__AMP_SERVICES;c||(c=a.__AMP_SERVICES={});a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function ra(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)};function H(){this.ba=100;this.P=this.V=0;this.L=Object.create(null)}H.prototype.has=function(a){return!!this.L[a]};H.prototype.get=function(a){var b=this.L[a];if(b)return b.access=++this.P,b.payload};
H.prototype.put=function(a,b){this.has(a)||this.V++;this.L[a]={payload:b,access:this.P};if(!(this.V<=this.ba)){if(y.dev)a=y.dev;else throw Error("failed to call initLogConstructor");a.warn("lru-cache","Trimming LRU cache");a=this.L;var c=this.P+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.V--)}};var sa=C({c:!0,v:!0,a:!0,ad:!0}),I,ta,ua=/[?&]amp_js[^&]*/,va=/[?&]amp_gsa[^&]*/,wa=/[?&]amp_r[^&]*/,xa=/[?&]amp_kit[^&]*/,ya=/[?&]usqp[^&]*/;
function J(a){I||(I=self.document.createElement("a"),ta=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new H));var b=ta,c=I;if(b&&b.has(a))a=b.get(a);else{c.href=a;c.protocol||(c.href=c.href);var d={href:c.href,protocol:c.protocol,host:c.host,hostname:c.hostname,port:"0"==c.port?"":c.port,pathname:c.pathname,search:c.search,hash:c.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;d.origin=
c.origin&&"null"!=c.origin?c.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;b&&b.put(a,d);a=d}return a}function za(a,b,c){b=encodeURIComponent(b)+"="+encodeURIComponent(c);b&&(a=a.split("#",2),c=a[0].split("?",2),b=c[0]+(c[1]?"?"+c[1]+"&"+b:"?"+b),a=b+=a[1]?"#"+a[1]:"");return a}
function Aa(a){var b=[],c;for(c in a){var d=a[c];if(null!=d)if(w(d))for(var e=0;e<d.length;e++){var f=d[e];b.push(encodeURIComponent(c)+"="+encodeURIComponent(f))}else e=d,b.push(encodeURIComponent(c)+"="+encodeURIComponent(e))}return b.join("&")}
function Ea(a,b){var c=void 0===c?"source":c;A(null!=a,"%s %s must be available",b,c);var d=a;"string"==typeof d&&(d=J(d));var e;(e="https:"==d.protocol||"localhost"==d.hostname||"127.0.0.1"==d.hostname)||(d=d.hostname,e=d.length-10,e=0<=e&&d.indexOf(".localhost",e)==e);A(e||/^(\/\/)/.test(a),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,a)};function Fa(a,b){void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};function Ga(a){return!!a&&"function"==typeof a.getFormData};var Ha=["GET","POST"],Ia=[w,function(a){return"[object Object]"===ea.call(a)}];function Ja(a){a=a||{};var b=a.method;void 0===b?b="GET":(b=b.toUpperCase(),Ha.includes(b));a.method=b;a.headers=a.headers||C({});a.headers.Accept="application/json";return a}
function Ka(a){var b=Ja(a);"POST"!=b.method||Ga(b.body)||(ka(Ia.some(function(c){return c(b.body)})),b.headers["Content-Type"]=b.headers["Content-Type"]||"text/plain;charset=utf-8",b.body="application/x-www-form-urlencoded"===b.headers["Content-Type"]?Aa(b.body):JSON.stringify(b.body))};function K(a,b){this.O=a;this.F=b;this.ea="amp-autocomplete"}K.prototype.isEnabled=function(){var a=this.O.getAmpDoc();return a.isSingleDoc()&&a.getRootNode().documentElement.hasAttribute("allow-viewer-render-template")?this.O.hasCapability("viewerRenderTemplate"):!1};K.prototype.assertTrustedViewer=function(a){return this.O.isTrustedViewer().then(function(b){A(b,"Refused to attempt SSR in untrusted viewer: ",a)})};
K.prototype.ssr=function(a,b,c,d){var e=this;c=void 0===c?null:c;d=void 0===d?{}:d;var f=c,g=d,h;f||(h=this.F.maybeFindTemplate(a));return this.assertTrustedViewer(a).then(function(){return e.O.sendMessageAwaitResponse("viewerRenderTemplate",La(e,b,h,f,g))})};
K.prototype.applySsrOrCsrTemplate=function(a,b){var c=this;if(this.isEnabled()){A("string"===typeof b.html,"Server side html response must be defined");var d=this.assertTrustedViewer(a).then(function(){return c.F.findAndSetHtmlForTemplate(a,b.html)})}else d=w(b)?this.F.findAndRenderTemplateArray(a,b):this.F.findAndRenderTemplate(a,b);return d};
function La(a,b,c,d,e){var f=e=void 0===e?{}:e,g=C({type:a.ea}),h=d&&d.successTemplate?d.successTemplate:c;h&&(g.successTemplate={type:"amp-mustache",payload:h.innerHTML});var k=d&&d.errorTemplate?d.errorTemplate:null;k&&(g.errorTemplate={type:"amp-mustache",payload:k.innerHTML});f&&Object.assign(g,f);a=b.xhrUrl;c=b.fetchOpt;b=Object.assign({},c);if(Ga(c.body)){c=c.body;b.headers["Content-Type"]="multipart/form-data;charset=utf-8";c=c.entries();d=[];for(e=c.next();!e.done;e=c.next())d.push(e.value);
b.body=d}return C({originalRequest:{input:a,init:b},ampComponent:g})};function L(a,b){if("."==b)return a;b=b.split(".");for(var c=0;c<b.length;c++){var d=b[c];if(d&&a&&void 0!==a[d]&&(null==a||"object"!=typeof a?0:Object.prototype.hasOwnProperty.call(a,d)))a=a[d];else{a=void 0;break}}return a}function Ma(a,b){try{return JSON.parse(a)}catch(c){return b&&b(c),null}};function Na(a,b,c){c=void 0===c?{}:c;var d=void 0===c.expr?".":c.expr,e=void 0===c.urlReplacement?0:c.urlReplacement,f=void 0===c.refresh?!1:c.refresh,g=void 0===c.xssiPrefix?void 0:c.xssiPrefix;Ea(b.getAttribute("src"),b);var h=E(a.win,"batched-xhr");return Oa(b,e,f).then(function(k){return h.fetchJson(k.xhrUrl,k.fetchOpt)}).then(function(k){return E(a.win,"xhr").xssiJson(k,g)}).then(function(k){if(null==k)throw Error("Response is undefined.");return L(k,d||".")}).catch(function(k){throw z().createError("failed fetching JSON data",
k);})}
function Oa(a,b,c){var d=a.getAttribute("src"),e=qa(a,"url-replace");return(1<=b?e.expandUrlAsync(d):Promise.resolve(d)).then(function(f){if(1==b){var g=e.collectDisallowedVarsSync(a);if(0<g.length)throw z().createError('URL variable substitutions in CORS fetches from dynamic URLs (e.g. via amp-bind) require opt-in. Please add data-amp-replace="'+(g.join(" ")+'" to the <')+(a.tagName+"> element. See https://bit.ly/amp-var-subs."));}var h={};a.hasAttribute("credentials")&&(h.credentials=a.getAttribute("credentials"));c&&
(h.cache="reload");return{xhrUrl:f,fetchOpt:h}})};function Pa(a,b,c,d){var e={detail:c};Object.assign(e,d);if("function"==typeof a.CustomEvent)return new a.CustomEvent(b,e);a=a.document.createEvent("CustomEvent");a.initCustomEvent(b,!!e.bubbles,!!e.cancelable,c);return a};function Qa(a){var b=a.documentElement;return["\u26a14email","amp4email"].some(function(c){return b.hasAttribute(c)})};function Ra(a,b){return 0<a&&0<b?a%b:(a%b+b)%b};function Sa(a,b){var c=b.length,d=a.length;if(d>c)return!1;if(d===c&&a===b)return!0;var e=0,f=0;a:for(;e<d;e++){for(var g=a.charCodeAt(e);f<c;)if(b.charCodeAt(f++)===g)continue a;return!1}return!0};var Ta={SUBSTRING:"substring",PREFIX:"prefix",TOKEN_PREFIX:"token-prefix",FUZZY:"fuzzy",CUSTOM:"custom",NONE:"none"};
function M(a){var b=AMP.BaseElement.call(this,a)||this;b.A=null;b.o=null;b.h=null;b.j="";b.C="";b.$=1;b.K=null;b.B=!1;b.S=!1;b.Z=!1;b.N="";b.M="";b.G=-1;b.l=null;b.ca=a.id?a.id:Math.floor(100*Math.random());b.m=null;b.I=!1;b.U=null;b.F=E(b.win,"templates");b.T=!1;b.getSsrTemplateHelper=fa(function(){return new K(oa(b.element,"viewer"),b.F)});b.J=!1;b.W=null;b.aa=null;b.Y=!1;b.R=a.id?a.id:Math.floor(100*Math.random())+"_AMP_content_";return b}var N=AMP.BaseElement;M.prototype=aa(N.prototype);
M.prototype.constructor=M;if(r)r(M,N);else for(var O in N)if("prototype"!=O)if(Object.defineProperties){var Ua=Object.getOwnPropertyDescriptor(N,O);Ua&&Object.defineProperty(M,O,Ua)}else M[O]=N[O];M.ga=N.prototype;
M.prototype.buildCallback=function(){var a=this.element.ownerDocument,b=a&&Qa(a);A(!b||a.documentElement.hasAttribute("data-amp-autocomplete-opt-in"),"<amp-autocomplete> is not currently available in AMP4Email.");this.W=qa(this.element,"action");this.aa=oa(this.element,"viewport");a=this.element.querySelectorAll("input,textarea");A(1==a.length,"%s should contain exactly one <input> or <textarea> descendant %s","amp-autocomplete",this.element);this.h=a[0];var c=this.h.getAttribute("type");A(!this.h.hasAttribute("type")||
"text"===c||"search"===c,'%s requires the "type" attribute to be "text" or "search" if present on <input>. %s',"amp-autocomplete",this.element);this.A=this.element.hasAttribute("inline")?new ma(this):new na(this);this.M=this.element.getAttribute("query");this.N=this.element.getAttribute("src");var d=this.element.querySelector('script[type="application/json"]');d?this.o=Va(this,d):this.element.hasAttribute("src")||z().warn("amp-autocomplete",'Expected a <script type="application/json"> child or a URL specified in "src".');
this.h.setAttribute("dir","auto");this.h.setAttribute("aria-autocomplete","both");this.h.setAttribute("role","textbox");this.h.setAttribute("aria-controls",this.R);"INPUT"===this.h.tagName&&(this.element.setAttribute("role","combobox"),this.h.setAttribute("aria-multiline","false"));this.element.setAttribute("aria-haspopup","listbox");this.element.setAttribute("aria-expanded","false");this.element.setAttribute("aria-owns",this.R);(a=this.h.form||null)&&a.hasAttribute("autocomplete")&&(this.U=a.getAttribute("autocomplete"));
this.J=this.getSsrTemplateHelper().isEnabled();this.T=this.F.hasTemplate(this.element,"template, script[template]");this.J&&(A(this.N,'%s requires data to be provided via "src" attribute for server-side rendering. %s',"amp-autocomplete",this.element),A(this.T,'amp-autocomplete should provide a <template> or <script type="plain/text"> element.'),A(!this.element.hasAttribute("filter"),"amp-autocomplete does not support client-side filter when server-side render is required."));this.C=this.element.getAttribute("filter")||
"none";a:{for(e in Ta)if(Ta[e]===this.C){var e=!0;break a}e=!1}A(e,"Unexpected filter: %s. %s",this.C,this.element);this.$=this.element.hasAttribute("min-characters")?parseInt(this.element.getAttribute("min-characters"),10):1;this.element.hasAttribute("max-entries")&&z().warn("amp-autocomplete",'"max-items" attribute is preferred to "max-entries"');var f=this.element.getAttribute("max-items")||this.element.getAttribute("max-entries");this.K=f?parseInt(f,10):null;this.B=this.A.shouldSuggestFirst();
this.Z=this.element.hasAttribute("highlight-user-entry");e=this.element.ownerDocument.createElement("div");e.classList.add("i-amphtml-autocomplete-results");Wa(this)&&e.classList.add("i-amphtml-autocomplete-results-up");e.setAttribute("role","listbox");e.setAttribute("id",this.R);Fa(e,!1);this.m=e;this.element.appendChild(this.m);Xa(this);return u()};
function Xa(a){a.h.addEventListener("touchstart",function(){P(a)},{passive:!0});a.h.addEventListener("input",function(){Ya(a)});a.h.addEventListener("keydown",function(b){Za(a,b)});a.h.addEventListener("focus",function(){P(a).then(function(){var b=a.A.shouldShowOnFocus();$a(a,b)})});a.h.addEventListener("blur",function(){$a(a,!1)});a.m.addEventListener("mousedown",function(b){ab(a,b)})}
function Va(a,b){b=Ma(b.textContent,function(e){throw e;});var c=a.element.getAttribute("items")||"items",d=L(b,c);return d?z().assertArray(d):(z().warn("amp-autocomplete",'Expected key "%s" in data but found nothing. Rendering empty results.',c),[])}
function Q(a){var b=a.getAmpDoc(),c=a.element.getAttribute("items")||"items";bb(a);return a.J?Oa(a.element,2,!1).then(function(d){var e=a.win,f=d.xhrUrl;if(!1!==d.fetchOpt.ampCors){var g=J(f).search,h=Object.create(null);if(g)for(var k;k=da.exec(g);){var p=v(k[1],k[1]);k=k[2]?v(k[2].replace(/\+/g," "),k[2]):"";h[p]=k}A(!("__amp_source_origin"in h),"Source origin is not allowed in %s",f);e=e.location.href;"string"==typeof e&&(e=J(e));g=e;"string"==typeof g&&(g=J(g));ja.cdnProxyRegex.test(g.origin)?
(g=e.pathname.split("/"),A(sa[g[1]],"Unknown path prefix in url %s",e.href),h=g[2],p="s"==h?"https://"+decodeURIComponent(g[3]):"http://"+decodeURIComponent(h),A(0<p.indexOf("."),"Expected a . in origin %s",p),g.splice(1,"s"==h?3:2),g=p+g.join("/"),h=(h=e.search)&&"?"!=h?(h=h.replace(ua,"").replace(va,"").replace(wa,"").replace(xa,"").replace(ya,"").replace(/^[?&]/,""))?"?"+h:"":"",e=g+h+(e.hash||"")):e=e.href;e=J(e).origin;f=za(f,"__amp_source_origin",e)}d.xhrUrl=f;e=d.xhrUrl;f=(f=d.fetchOpt)||{};
g=a.win;g=g.origin||J(g.location.href).origin;e=J(e).origin;g==e&&(f.headers=f.headers||{},f.headers["AMP-Same-Origin"]="true");d.fetchOpt=f;Ka(d.fetchOpt);f=C({ampAutocompleteAttributes:{items:c,maxItems:a.K}});return a.getSsrTemplateHelper().ssr(a.element,d,null,f)}):Na(b,a.element,{expr:c,urlReplacement:2}).catch(function(){z().warn("amp-autocomplete",'Expected key "%s" in data but found nothing. Rendering empty results.',c);return[]})}
function bb(a){if(a.M){var b=a.j;b=za(a.N,a.M,void 0===b?"":b);a.element.setAttribute("src",b)}}M.prototype.layoutCallback=function(){this.h.setAttribute("autocomplete","off");this.element.hasAttribute("prefetch")&&P(this);return R(this,this.o,this.j)};
M.prototype.mutatedAttributesCallback=function(a){var b=this,c=a.src;if(void 0===c||null===c)return u();if("string"===typeof c)return this.N=c,Q(this).then(function(d){b.o=d||[];R(b,b.o,b.j)},function(d){cb(b,d)});if("object"===typeof c)return this.o=c.items||[],R(this,this.o,this.j);z().error("amp-autocomplete",'Unexpected "src" type: '+c)};
function db(a,b,c){var d=void 0===c?"":c;c=a.element.ownerDocument.createElement("div");c.classList.add("i-amphtml-autocomplete-item");c.setAttribute("role","option");c.setAttribute("data-value",b);c.setAttribute("dir","auto");c.textContent=b;var e=c.childNodes[0],f=b.toLocaleLowerCase(),g=d.toLocaleLowerCase();if(a.Z&&d&&d.length<=b.length&&la(f,g)){var h=f.indexOf(g),k=a.element.ownerDocument.createElement("span");k.classList.add("autocomplete-partial");k.appendChild(a.element.ownerDocument.createTextNode(b.slice(h,
h+d.length)));var p=e.splitText(h);p.splitText(d.length);c.replaceChild(k,p)}return c}function Ya(a){a.A.shouldAutocomplete(a.h)?eb(a):a.mutateElement(function(){S(a)})}function eb(a){var b=0===a.j.length&&1===a.h.value.length;a.j=a.A.getUserInputForUpdate(a.h);(a.J||a.M?Q(a):Promise.resolve(a.o)).then(function(c){a.o=c;return a.mutateElement(function(){R(a,a.o,a.j).then(function(){T(a,!0);a.B&&(a.S&&!b||U(a,1),a.S=!1)})})})}
function ab(a,b){var c=fb(a,b.target);b=V(a,c);var d=b.selectedObject,e=b.selectedText;a.mutateElement(function(){W(a,e,d)})}function R(a,b,c){var d=c=void 0===c?"":c;S(a);return!b||d.length<a.$?u():a.J?B.call(b,"html")?gb(a,b,a.m,d):u():hb(a,b,d)}function hb(a,b,c){if(!b.length)return u();var d=ib(a,b,c).map(function(e){var f=e;"object"===typeof e&&(f=Object.assign({},e,{objToJson:function(){return JSON.stringify(e)}}));return f});return gb(a,d,a.m,c)}
function gb(a,b,c,d){var e=u();X(a);a.T?e=a.getSsrTemplateHelper().applySsrOrCsrTemplate(a.element,b).then(function(f){(w(f)?f:[f]).forEach(function(g){g.hasAttribute("data-disabled")?g.setAttribute("aria-disabled","true"):g.hasAttribute("data-value")||z().warn("amp-autocomplete",'Expected a "data-value" or "data-disabled" attribute on the rendered template item. %s',g);g.classList.add("i-amphtml-autocomplete-item");g.setAttribute("role","option");c.appendChild(g)})}):b.forEach(function(f){A("string"===
typeof f,"%s data must provide template for non-string items. %s","amp-autocomplete",a.element);c.appendChild(db(a,f,d))});return e}
function ib(a,b,c){if("none"===a.C)return jb(a,b);c=c.toLocaleLowerCase();var d=a.element.getAttribute("filter-value")||"value";b=b.filter(function(e){"object"===typeof e&&(e=L(e,d));A("string"===typeof e,'%s data property "%s" must map to string type. %s',"amp-autocomplete",d,a.element);e=e.toLocaleLowerCase();switch(a.C){case "substring":return la(e,c);case "prefix":return e.startsWith(c);case "token-prefix":return kb(e,c);case "fuzzy":return Sa(c,e);case "custom":throw Error("Filter not yet supported: %s",
a.C,a.element);default:throw Error("Unexpected filter: %s",a.C,a.element);}});return jb(a,b)}function kb(a,b){if(""===b)return!0;var c=lb(a),d=lb(b),e=mb(c),f=d[d.length-1];d.splice(d.length-1,1);a=!0;for(b=0;b<d.length;b++){var g=d[b];if(""!==g){if(!B.call(e,g)){a=!1;break}var h=Number(D(e,g));1<h?e[g]=h-1:delete e[g]}}var k=Object.keys(e);return a&&(""===f||k.some(function(p){return p.startsWith(f)}))}function lb(a){a=a.replace(/[\.]+/g,"");return a.split(/[`~(){}_|+\-;:'",\[\]\\\/ ]+/g)}
function mb(a){var b=Object.create(null);a.forEach(function(c){var d=B.call(b,c)?D(b,c)+1:1;b[c]=d});return b}function jb(a,b){a.K&&a.K<b.length&&(b=b.slice(0,a.K));return b}function T(a,b){a.h.setAttribute("aria-expanded",b);Fa(a.m,b)}
function $a(a,b){var c=a.h.form||null;c&&(b?c.setAttribute("autocomplete","off"):a.U?c.setAttribute("autocomplete",a.U):c.removeAttribute("autocomplete"));var d=!1;a.measureMutateElement(function(){d=Wa(a)},function(){b||(a.j=a.h.value,R(a,a.o,a.j),X(a));a.m.classList.toggle("i-amphtml-autocomplete-results-up",d);T(a,b)})}function P(a){if(a.Y||!a.element.hasAttribute("src"))return u();a.Y=!0;return Q(a).then(function(b){a.o=b;R(a,a.o)},function(b){cb(a,b)})}
function Wa(a){var b=a.aa.getHeight()||0;return a.h.getBoundingClientRect().top>b/2}function Y(a){return!a.m.hasAttribute("hidden")&&0<a.m.children.length}function fb(a,b){return null===b?null:b.classList.contains("i-amphtml-autocomplete-item")?b:fb(a,b.parentElement)}
function V(a,b){if(null===b||b.hasAttribute("data-disabled"))return{selectedObject:null,selectedText:null};var c=b.getAttribute("data-value")||b.textContent||"";a.h.value=a.A.getUserInputForUpdateWithSelection(c,a.h,a.j);a.j=a.A.getUserInputForUpdate(a.h);return{selectedObject:nb(b),selectedText:c}}function nb(a){return a.hasAttribute("data-json")?Ma(a.getAttribute("data-json"),function(b){throw b;}):null}
function W(a,b,c){null!==b&&(b=Object.assign({},{value:b},c&&{valueAsObject:c}),c=Pa(a.win,"amp-autocomplete.select",b),a.W.trigger(a.element,"select",c,3),b=Pa(a.win,"change",b,{bubbles:!0}),a.h.dispatchEvent(b),S(a),T(a,!1))}
function U(a,b){if(0===b||!Y(a)||a.I)u();else{var c=-1===a.G&&0>b?b:a.G+b,d=ob(a);if(0===d.length)u();else{var e=Ra(c,d.length),f=d[e];c=f.getAttribute("data-value");a.A.displayActiveItemInInput(a.h,c,a.j);var g,h;a.measureMutateElement(function(){var k=f.offsetTop,p=f.offsetHeight,Ba=a.m,Ca=Ba.scrollTop,Da=Ba.offsetHeight;g=Ca>k||Ca+Da<k+p;h=0<b?k+p-Da:k},function(){g&&(a.m.scrollTop=h);X(a);f.classList.add("i-amphtml-autocomplete-item-active");f.setAttribute("aria-selected","true");var k=f.getAttribute("id");
k||(k=a.ca+"_AMP_content_"+e,f.setAttribute("id",k));a.h.setAttribute("aria-activedescendant",k);a.G=e;a.l=f;try{a.l.focus()}catch(p){}})}}}function ob(a){return a.m.querySelectorAll(".i-amphtml-autocomplete-item:not([data-disabled])")}function Z(a){a.A.resetInputOnWrapAround(a.j,a.h);X(a)}
function X(a){a.l&&(a.l.classList.toggle("i-amphtml-autocomplete-item-active",!1),a.l.removeAttribute("aria-selected"),"autocomplete-selected"===a.l.getAttribute("id")&&a.l.removeAttribute("id"),a.h.removeAttribute("aria-activedescendent"),a.l=null,a.G=-1)}function S(a){a.I=!1;for(a=a.m;a.firstChild;)a.removeChild(a.firstChild)}
function Za(a,b){switch(b.key){case "ArrowDown":b.preventDefault();if(Y(a)){if(a.G===ob(a).length-1){Z(a);u();break}U(a,1);break}a.mutateElement(function(){R(a,a.o,a.j);T(a,!0)});break;case "ArrowUp":b.preventDefault();if(0===a.G){Z(a);u();break}U(a,-1);break;case "Enter":var c=a.A.shouldPreventDefaultOnEnter(!!a.l);Y(a)&&c&&b.preventDefault();a.A.removeSelectionHighlighting(a.h);if(Y(a)&&a.l){var d=V(a,a.l),e=d.selectedObject,f=d.selectedText;a.mutateElement(function(){W(a,f,e);X(a)});break}a.mutateElement(function(){T(a,
!1)});break;case "Escape":a.mutateElement(function(){a.I||(b.preventDefault(),Z(a),T(a,!1))});break;case "Tab":if(Y(a)&&a.l){b.preventDefault();d=V(a,a.l);var g=d.selectedObject,h=d.selectedText;a.mutateElement(function(){W(a,h,g)});break}u();break;case "Backspace":a.S=a.B;u();break;default:u()}}function cb(a,b){if(!a.I)if(S(a),a.getFallback())a.I=!0,a.toggleFallback(!0);else throw b;}M.prototype.isLayoutSupported=function(a){return"container"==a};
(function(a){a.registerElement("amp-autocomplete",M,"amp-autocomplete,amp-autocomplete>input,amp-autocomplete>textarea{font-family:sans-serif}amp-autocomplete>input,amp-autocomplete>textarea{border-radius:4px;box-sizing:border-box}.i-amphtml-autocomplete-results{position:absolute;top:100%;width:calc(100% + 1rem);min-width:calc(2em + 2rem);max-height:40vh;margin-top:.5rem;margin-left:-.5rem;border-radius:4px;overflow-y:auto;overflow-x:hidden;background-color:#fff;box-shadow:0px 2px 4px 0px rgba(0,0,0,0.5);z-index:10}.i-amphtml-autocomplete-results-up{top:auto;bottom:100%;margin-bottom:.5rem}.i-amphtml-autocomplete-item{position:relative;padding:.5rem 1rem;cursor:pointer}.i-amphtml-autocomplete-item:first-child{border-radius:4px 4px 0px 0px}.i-amphtml-autocomplete-item:nth-last-child(2){border-radius:0px 0px 4px 4px}.i-amphtml-autocomplete-item-active:not([data-disabled]),.i-amphtml-autocomplete-item:hover:not([data-disabled]){background-color:rgba(0,0,0,0.15)}.i-amphtml-autocomplete-item[data-disabled]{color:rgba(0,0,0,0.33)}\n/*# sourceURL=/extensions/amp-autocomplete/0.1/amp-autocomplete.css*/")})(self.AMP);
})});

//# sourceMappingURL=amp-autocomplete-0.1.js.map
