(self.AMP=self.AMP||[]).push({n:"amp-nested-menu",v:"2011252111002",f:(function(AMP,_){
'use strict';var f,g="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function k(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}k(this);"function"===typeof Symbol&&Symbol("x");var l;
if("function"==typeof Object.setPrototypeOf)l=Object.setPrototypeOf;else{var m;a:{var n={a:!0},p={};try{p.__proto__=n;m=p.a;break a}catch(a){}m=!1}l=m?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var q=l,r;function t(a){return a?Array.prototype.slice.call(a):[]};var u=self.AMP_CONFIG||{},v=("string"==typeof u.cdnProxyRegex?new RegExp(u.cdnProxyRegex):u.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function w(a){if(self.document&&self.document.head&&(!self.location||!v.test(self.location.origin))){var b=self.document.head.querySelector('meta[name="'+a+'"]');b&&b.getAttribute("content")}}u.cdnUrl||w("runtime-host");u.geoApiUrl||w("amp-geo-api");self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var x=self.__AMP_LOG;function y(a,b){if(!x.user)throw Error("failed to call initLogConstructor");x.user.assert(a,b,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function z(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return A(a,b)}function B(a){return a.nodeType?z((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function A(a,b){C(a,b);var c=a.__AMP_SERVICES;c||(c=a.__AMP_SERVICES={});a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function C(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)};(function(a){return a||{}})({c:!0,v:!0,a:!0,ad:!0});/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var D;function E(a,b,c){for(;a&&a!==c;a=a.parentElement)if(b(a))return a;return null}function F(a,b){return a.closest?a.closest(b):E(a,function(c){var d=c.matches||c.webkitMatchesSelector||c.mozMatchesSelector||c.msMatchesSelector||c.oMatchesSelector;return d?d.call(c,b):!1})}
function G(a,b){if(void 0!==D)var c=D;else{try{var d=a.ownerDocument,e=d.createElement("div"),h=d.createElement("div");e.appendChild(h);c=e.querySelector(":scope div")===h}catch(T){c=!1}c=D=c}if(c)return a.querySelector(b.replace(/^|,/g,"$&:scope "));a.classList.add("i-amphtml-scoped");b=b.replace(/^|,/g,"$&.i-amphtml-scoped ");b=a.querySelectorAll(b);a.classList.remove("i-amphtml-scoped");return void 0===b[0]?null:b[0]}function H(a){try{a.focus()}catch(b){}};function I(a){var b=AMP.BaseElement.call(this,a)||this;b.A=b.win.document;b.l=null;b.h=null;b.j=a;b.o=b.m.bind(b);b.C=b.B.bind(b);return b}var J=AMP.BaseElement;I.prototype=g(J.prototype);I.prototype.constructor=I;if(q)q(I,J);else for(var K in J)if("prototype"!=K)if(Object.defineProperties){var L=Object.getOwnPropertyDescriptor(J,K);L&&Object.defineProperty(I,K,L)}else I[K]=J[K];I.D=J.prototype;f=I.prototype;
f.buildCallback=function(){var a=this.element,b=B(this.element);b=B(b);b=b.isSingleDoc()?b.win:b;this.l=C(b,"action")?A(b,"action"):null;this.h=a.getAttribute("side");"left"!=this.h&&"right"!=this.h&&(b=this.A,this.h="rtl"==(b.body.getAttribute("dir")||b.documentElement.getAttribute("dir")||"ltr")?"left":"right",a.setAttribute("side",this.h));this.registerAction("reset",this.reset.bind(this));a.addEventListener("click",this.o);a.addEventListener("keydown",this.C)};
f.layoutCallback=function(){M(this);r||(r=Promise.resolve(void 0));var a=r;return a};function M(a){t(a.element.querySelectorAll("[amp-nested-submenu-open],[amp-nested-submenu-close]")).forEach(function(b){b.hasAttribute("tabindex")||b.setAttribute("tabindex",0);b.setAttribute("role","button");b.hasAttribute("amp-nested-submenu-open")&&b.setAttribute("aria-expanded","false");y(0==a.l.hasAction(b,"tap"),"submenu open/close buttons should not have tap actions registered.")})}
f.isLayoutSupported=function(a){return"fill"==a};f.prerenderAllowed=function(){return!0};f.m=function(a){var b=a.target;(a=F(a.target,"[amp-nested-submenu-open],[amp-nested-submenu-close]"))&&N(this,b,a)&&(a.hasAttribute("amp-nested-submenu-open")?O(this,a):(b=F(a,"[amp-nested-submenu]"),y(b,"amp-nested-menu: submenu close buttons are only allowed inside submenus"),P(this,b)))};function N(a,b,c){var d=!!E(b,function(h){return"A"==h.tagName},c),e=a.l.hasAction(b,"tap",c);return!d&&!e}
function O(a,b){var c=G(b.parentElement,">[amp-nested-submenu]");y(c,"amp-nested-menu requires each submenu open button to have a submenu as its sibling");Q(a,c)}
function Q(a,b){if(!b.hasAttribute("open")){var c=R(b);c&&(c.setAttribute("child-open",""),b.setAttribute("open",""),a.j=b,z(a.win,"timer").delay(function(){G(b.parentElement,">[amp-nested-submenu-open]").setAttribute("aria-expanded","true");var d=t(b.querySelectorAll("[amp-nested-submenu-close]")).filter(function(e){return R(e)==b})[0];y(d,"amp-nested-menu requires each submenu to contain at least one submenu close button");H(d)},350))}}
function P(a,b){if(b.hasAttribute("open")){var c=R(b);c&&(c.removeAttribute("child-open"),b.removeAttribute("open"),a.j=c,z(a.win,"timer").delay(function(){var d=G(b.parentElement,">[amp-nested-submenu-open]");d.setAttribute("aria-expanded","false");H(d)},350))}}f.reset=function(){for(;this.element.hasAttribute("child-open");)P(this,this.j)};
f.B=function(a){if(!a.defaultPrevented)switch(a.key){case "Enter":case " ":this.m(a);break;case "ArrowLeft":case "ArrowRight":var b="ArrowLeft"==a.key;"left"==this.h&&(b=!b);b?P(this,this.j):(a=a.target,a.hasAttribute("amp-nested-submenu-open")&&O(this,a));break;case "ArrowUp":case "ArrowDown":case "Home":case "End":S(a)}};
function S(a){var b=a.target,c=R(b);if(b=E(b,function(h){return"LI"==h.tagName},c)){if("ArrowUp"===a.key)var d=b.previousElementSibling;else if("ArrowDown"===a.key)d=b.nextElementSibling;else if("Home"===a.key)d=b.parentElement.firstElementChild;else if("End"===a.key)d=b.parentElement.lastElementChild;else return;if(d){var e=d.querySelector("button,a[href],[tabindex]");e&&(a.preventDefault(),H(e))}}}function R(a){return F(a.parentElement,"amp-nested-menu,[amp-nested-submenu]")}
(function(a){a.registerElement("amp-nested-menu",I,"amp-nested-menu,amp-nested-menu [amp-nested-submenu]{position:absolute!important;top:0!important;width:100%!important;height:100%!important;margin:0!important;padding:0!important;transform:translateX(0)!important}amp-nested-menu.i-amphtml-layout-size-defined{overflow:visible!important}amp-nested-menu ol,amp-nested-menu ul{list-style-type:none;padding:0}amp-nested-menu [amp-nested-submenu-close],amp-nested-menu [amp-nested-submenu-open]{cursor:pointer}amp-nested-menu [amp-nested-submenu]{opacity:0!important;visibility:hidden!important;transition:transform 233ms,opacity 233ms,visibility 0s 233ms}amp-nested-menu,amp-nested-menu [amp-nested-submenu][open]{opacity:1!important;visibility:visible!important;transition:transform 233ms}amp-nested-menu [amp-nested-submenu][child-open],amp-nested-menu[child-open]{visibility:hidden!important;transition:transform 233ms,visibility 0s 233ms}amp-nested-menu[side=left] [amp-nested-submenu]{right:100%!important}amp-nested-menu[side=right] [amp-nested-submenu]{left:100%!important}amp-nested-menu[side=left] [amp-nested-submenu][child-open],amp-nested-menu[side=left][child-open]{transform:translateX(100%)!important}amp-nested-menu[side=right] [amp-nested-submenu][child-open],amp-nested-menu[side=right][child-open]{transform:translateX(-100%)!important}\n/*# sourceURL=/extensions/amp-nested-menu/0.1/amp-nested-menu.css*/")})(self.AMP);
})});

//# sourceMappingURL=amp-nested-menu-0.1.js.map
