(self.AMP=self.AMP||[]).push({n:"amp-accordion",v:"2011252111002",f:(function(AMP,_){
'use strict';var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function ca(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}ca(this);"function"===typeof Symbol&&Symbol("x");var m;
if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var da={a:!0},p={};try{p.__proto__=da;n=p.a;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var q=m;function r(a,b){var c=b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(d){return c}};var ea=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;var t=self.AMP_CONFIG||{},fa=("string"==typeof t.cdnProxyRegex?new RegExp(t.cdnProxyRegex):t.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function u(a){if(self.document&&self.document.head&&(!self.location||!fa.test(self.location.origin))){var b=self.document.head.querySelector('meta[name="'+a+'"]');b&&b.getAttribute("content")}}t.cdnUrl||u("runtime-host");t.geoApiUrl||u("amp-geo-api");self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var v=self.__AMP_LOG;function w(){if(!v.user)throw Error("failed to call initLogConstructor");return v.user}function x(){if(v.dev)return v.dev;throw Error("failed to call initLogConstructor");}function y(a,b,c){w().assert(a,b,c,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function ha(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};function z(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return A(a,b)}function ia(a){a=B(a);a=B(a);a=a.isSingleDoc()?a.win:a;return C(a,"action")?A(a,"action"):null}function B(a){return a.nodeType?z((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function A(a,b){C(a,b);var c=a.__AMP_SERVICES;c||(c=a.__AMP_SERVICES={});a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}
function C(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function ja(a,b,c){for(;a&&a!==c;a=a.parentElement)if(b(a))return a;return null};function D(a,b,c,d){var e=new E(a,b,c,d);return e.solveYValueFromXValue.bind(e)}function E(a,b,c,d){this.y0=this.x0=0;this.x1=a;this.y1=b;this.x2=c;this.y2=d;this.y3=this.x3=1}E.prototype.solveYValueFromXValue=function(a){return this.getPointY(this.solvePositionFromXValue(a))};
E.prototype.solvePositionFromXValue=function(a){var b=(a-this.x0)/(this.x3-this.x0);if(0>=b)return 0;if(1<=b)return 1;for(var c=0,d=1,e=0,f=0;8>f;f++){e=this.getPointX(b);var g=(this.getPointX(b+1E-6)-e)/1E-6;if(1E-6>Math.abs(e-a))return b;if(1E-6>Math.abs(g))break;else e<a?c=b:d=b,b-=(e-a)/g}for(f=0;1E-6<Math.abs(e-a)&&8>f;f++)e<a?(c=b,b=(b+d)/2):(d=b,b=(b+c)/2),e=this.getPointX(b);return b};
E.prototype.getPointX=function(a){if(0==a)return this.x0;if(1==a)return this.x3;var b=this.lerp(this.x0,this.x1,a),c=this.lerp(this.x1,this.x2,a),d=this.lerp(this.x2,this.x3,a);b=this.lerp(b,c,a);c=this.lerp(c,d,a);return this.lerp(b,c,a)};E.prototype.getPointY=function(a){if(0==a)return this.y0;if(1==a)return this.y3;var b=this.lerp(this.y0,this.y1,a),c=this.lerp(this.y1,this.y2,a),d=this.lerp(this.y2,this.y3,a);b=this.lerp(b,c,a);c=this.lerp(c,d,a);return this.lerp(b,c,a)};
E.prototype.lerp=function(a,b,c){return a+c*(b-a)};var ka=D(.25,.1,.25,1),la=D(.42,0,1,1),ma=D(0,0,.58,1),na=D(.42,0,.58,1),oa={linear:function(a){return a},ease:ka,"ease-in":la,"ease-out":ma,"ease-in-out":na};
function F(a){if(!a)return null;if("string"==typeof a){if(-1!=a.indexOf("cubic-bezier")){var b=a.match(/cubic-bezier\((.+)\)/);if(b&&(b=b[1].split(",").map(parseFloat),4==b.length)){for(var c=0;4>c;c++)if(isNaN(b[c]))return null;return D(b[0],b[1],b[2],b[3])}return null}return oa[a]}return a};function pa(){}function G(a){this.l=a;this.A=z(self,"vsync");this.F=null;this.c=[]}function qa(a,b,c){var d=ra;return(new G(a)).setCurve(d).add(0,b,1).start(c)}G.prototype.setCurve=function(a){a&&(this.F=F(a));return this};G.prototype.add=function(a,b,c,d){this.c.push({delay:a,func:b,duration:c,curve:F(d)});return this};G.prototype.start=function(a){return new H(this.A,this.l,this.c,this.F,a)};
function H(a,b,c,d,e){this.A=a;this.l=b;this.c=[];for(b=0;b<c.length;b++){var f=c[b];this.c.push({delay:f.delay,func:f.func,duration:f.duration,curve:f.curve||d,started:!1,completed:!1})}this.L=e;this.P=Date.now();this.B=!0;this.I={};c=new ha;this.H=c.promise;this.O=c.resolve;this.N=c.reject;this.J=this.A.createAnimTask(this.l,{mutate:this.R.bind(this)});this.A.canAnimate(this.l)?this.J(this.I):(x().warn("Animation","cannot animate"),I(this,!1,0))}
H.prototype.then=function(a,b){return a||b?this.H.then(a,b):this.H};H.prototype.thenAlways=function(a){a=a||pa;return this.then(a,a)};H.prototype.halt=function(a){I(this,!1,a||0)};function I(a,b,c){if(a.B){a.B=!1;if(0!=c){1<a.c.length&&a.c.sort(function(e,f){return e.delay+e.duration-(f.delay+f.duration)});try{if(0<c)for(c=0;c<a.c.length;c++)a.c[c].func(1,!0);else for(var d=a.c.length-1;0<=d;d--)a.c[d].func(0,!1)}catch(e){x().error("Animation","completion failed: "+e,e),b=!1}}b?a.O():a.N()}}
H.prototype.R=function(){if(this.B){for(var a=Date.now(),b=Math.min((a-this.P)/this.L,1),c=0;c<this.c.length;c++){var d=this.c[c];!d.started&&b>=d.delay&&(d.started=!0)}for(c=0;c<this.c.length;c++)if(d=this.c[c],d.started&&!d.completed)a:{var e;if(0<d.duration){var f=e=Math.min((b-d.delay)/d.duration,1);if(d.curve&&1!=f)try{f=d.curve(e)}catch(g){x().error("Animation","step curve failed: "+g,g);I(this,!1,0);break a}}else f=e=1;1==e&&(d.completed=!0);try{d.func(f,d.completed)}catch(g){x().error("Animation",
"step mutate failed: "+g,g),I(this,!1,0)}}1==b?I(this,!0,0):this.A.canAnimate(this.l)?this.J(this.I):(x().warn("Animation","cancel animation"),I(this,!1,0))}};function sa(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(e){x().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var d=0;d<c.length;d++)0!=c[d].length&&("-"==c[d][0]?a[c[d].substr(1)]=!1:a[c[d]]=!0);return a};var J,L="Webkit webkit Moz moz ms O o".split(" ");function M(a,b,c){if(b.startsWith("--"))return b;J||(J=Object.create(null));var d=J[b];if(!d||c){d=b;if(void 0===a[b]){var e=b.charAt(0).toUpperCase()+b.slice(1);a:{for(var f=0;f<L.length;f++){var g=L[f]+e;if(void 0!==a[g]){e=g;break a}}e=""}var h=e;void 0!==a[h]&&(d=h)}c||(J[b]=d)}return d}function N(a,b,c){(b=M(a.style,b,void 0))&&(b.startsWith("--")?a.style.setProperty(b,c):a.style[b]=c)}function O(a,b){for(var c in b)N(a,c,b[c])};function P(a,b){return function(c,d){for(var e in b){var f=e;"display"===f&&x().error("STYLE","`display` style detected. You must use toggle instead.");N(a,f,b[e](c,d))}}}function Q(a,b){return function(c){return a+(b-a)*c}}function R(a){return function(b){return a(b)+"px"}};var ta=D(.47,0,.745,.715),ra=D(.39,.575,.565,1);
function ua(a){if(a.__AMP__EXPERIMENT_TOGGLES)var b=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);b=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var c in a.AMP_CONFIG){var d=a.AMP_CONFIG[c];"number"===typeof d&&0<=d&&1>=d&&(b[c]=Math.random()<d)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(c=a.AMP_CONFIG["allow-doc-opt-in"],d=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){d=d.getAttribute("content").split(",");
for(var e=0;e<d.length;e++)-1!=c.indexOf(d[e])&&(b[d[e]]=!0)}Object.assign(b,sa(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length){c=a.AMP_CONFIG["allow-url-opt-in"];e=a.location.originalHash||a.location.hash;d=Object.create(null);if(e)for(var f;f=ea.exec(e);){var g=r(f[1],f[1]);f=f[2]?r(f[2].replace(/\+/g," "),f[2]):"";d[g]=f}for(e=0;e<c.length;e++)g=d["e-"+c[e]],"1"==g&&(b[c[e]]=!0),"0"==g&&(b[c[e]]=!1)}}return!!b["amp-accordion-display-locking"]&&
void 0!==a.document.body.onbeforematch}function S(a){var b=AMP.BaseElement.call(this,a)||this;b.o=[];b.C=null;b.m=null;b.D=!1;b.j=null;b.h=null;b.G=a.id?a.id:Math.floor(100*Math.random());return b}var T=AMP.BaseElement;S.prototype=ba(T.prototype);S.prototype.constructor=S;if(q)q(S,T);else for(var U in T)if("prototype"!=U)if(Object.defineProperties){var V=Object.getOwnPropertyDescriptor(T,U);V&&Object.defineProperty(S,U,V)}else S[U]=T[U];S.T=T.prototype;
S.prototype.isLayoutSupported=function(a){return"container"==a};S.prototype.prerenderAllowed=function(){return!0};
S.prototype.buildCallback=function(){var a=this;this.h=ia(this.element);this.D=this.element.hasAttribute("disable-session-states");this.C=va(this);this.m=wa(this);this.j=this.getRealChildren();this.j.forEach(function(b,c){y("section"==b.tagName.toLowerCase(),"Sections should be enclosed in a <section> tag, See https://github.com/ampproject/amphtml/blob/master/extensions/amp-accordion/amp-accordion.md. Found in: %s",a.element);var d=b.children;y(2==d.length,"Each section must have exactly two children. See https://github.com/ampproject/amphtml/blob/master/extensions/amp-accordion/amp-accordion.md. Found in: %s",
a.element);var e=d["0"],f=d["1"];f.classList.add("i-amphtml-accordion-content");var g=f.getAttribute("id");g||(g=a.G+"_AMP_content_"+c,f.setAttribute("id",g));var h=e.getAttribute("id");h||(h=a.G+"_AMP_header_"+c,e.setAttribute("id",h));a.registerAction("toggle",function(k){return W(a,k)});a.registerAction("expand",function(k){return W(a,k)});a.registerAction("collapse",function(k){return W(a,k)});a.h.addToAllowlist("amp-accordion",["toggle","expand","collapse"],["email"]);(new a.win.MutationObserver(function(k){xa(a,
k)})).observe(b,{attributes:!0,attributeFilter:["data-expand"]});a.m[g]?b.setAttribute("expanded",""):!1===a.m[g]&&b.removeAttribute("expanded");a.mutateElement(function(){});var l=b.hasAttribute("expanded");e.classList.add("i-amphtml-accordion-header");e.setAttribute("role","button");e.setAttribute("aria-controls",g);e.setAttribute("aria-expanded",String(l));e.hasAttribute("tabindex")||e.setAttribute("tabindex",0);a.o.push(e);f.setAttribute("aria-labelledby",h);f.setAttribute("role","region");y(0==
a.h.hasAction(e,"tap",b),"amp-accordion headings should not have tap actions registered.");e.addEventListener("click",a.K.bind(a));e.addEventListener("keydown",a.M.bind(a));ua(a.win)&&(a.element.classList.add("i-amphtml-display-locking"),f.addEventListener("beforematch",function(){X(a,b,3,!0)}))})};
function W(a,b){var c=b.method,d=b.args,e=b.trust,f=void 0;"expand"===c?f=!0:"collapse"===c&&(f=!1);if(d){var g=d.section,h=a.getAmpDoc().getElementById(g);h=w().assertElement(h);y(h,"No element found with id: %s",g);X(a,h,e,f)}else for(c=0;c<a.j.length;c++)X(a,a.j[c],e,f)}function va(a){var b=a.element.id||a.element.getResourceId();a=a.win.location.href;var c=a.indexOf("#");a=-1==c?a:a.substring(0,c);return"amp-"+b+"-"+a}
function wa(a){if(a.D)return{};try{var b=a.win.sessionStorage.getItem(a.C);return b?JSON.parse(b):{}}catch(c){return x().fine("AMP-ACCORDION","Error setting session state: %s, %s",c.message,c.stack),{}}}function ya(a){if(!a.D){var b=JSON.stringify(a.m);try{a.win.sessionStorage.setItem(a.C,b)}catch(c){x().fine("AMP-ACCORDION","Error setting session state: %s, %s",c.message,c.stack)}}}
function Y(a,b,c,d){var e=a.win;var f="accordionSection."+b;var g={};var h={detail:g};Object.assign(h,void 0);"function"==typeof e.CustomEvent?f=new e.CustomEvent(f,h):(e=e.document.createEvent("CustomEvent"),e.initCustomEvent(f,!!h.bubbles,!!h.cancelable,g),f=e);a.h.trigger(c,b,f,d);a=a.element;c=a.ownerDocument.createEvent("Event");c.data={};c.initEvent(b,!0,!0);a.dispatchEvent(c)}
function X(a,b,c,d){var e=b.children,f=e[0];e=e[1].getAttribute("id");var g=b.hasAttribute("expanded"),h=void 0==d?!b.hasAttribute("expanded"):d;h&&b.hasAttribute("expanded")||!h&&!b.hasAttribute("expanded")||(a.element.hasAttribute("animate")?h?(f.setAttribute("aria-expanded","true"),za(a,b,c),a.element.hasAttribute("expand-single-section")&&a.j.forEach(function(l){l!=b&&(Z(a,l,c),l.children[0].setAttribute("aria-expanded","false"))})):(f.setAttribute("aria-expanded","false"),Z(a,b,c)):a.mutateElement(function(){h?
(Y(a,"expand",b,c),b.setAttribute("expanded",""),f.setAttribute("aria-expanded","true"),a.element.hasAttribute("expand-single-section")&&a.j.forEach(function(l){l!=b&&(l.hasAttribute("expanded")&&(Y(a,"collapse",l,c),l.removeAttribute("expanded")),l.children[0].setAttribute("aria-expanded","false"))})):(Y(a,"collapse",b,c),b.removeAttribute("expanded"),f.setAttribute("aria-expanded","false"))},b),a.m[e]=!g,ya(a))}
function za(a,b,c){var d,e,f,g,h,l=b.children[1];a.measureMutateElement(function(){d=b.offsetWidth;var k=M(l.style,"width",void 0);h=k?k.startsWith("--")?l.style.getPropertyValue(k):l.style[k]:void 0},function(){var k={position:"fixed",width:d+"px",opacity:"0"},aa=l.style,K;for(K in k)aa.setProperty(M(aa,K),k[K].toString(),"important");b.hasAttribute("expanded")||b.setAttribute("expanded","")}).then(function(){return a.measureMutateElement(function(){e=b.offsetHeight;f=l.offsetHeight;var k=a.getViewport().getHeight();
g=Aa(Math.abs(f),k)},function(){O(b,{overflow:"hidden",height:e+"px"});O(l,{position:"",opacity:"",width:h})})}).then(function(){var k=new G(a.element);k.setCurve(ta);k.add(0,P(b,{height:R(Q(e,e+f))}),1);k.add(0,P(l,{opacity:Q(0,1)}),1);return k.start(g).thenAlways(function(){a.mutateElement(function(){Y(a,"expand",b,c);O(b,{overflow:"",height:""});O(l,{opacity:""})})})})}
function Z(a,b,c){var d,e,f,g=b.firstElementChild;a.measureMutateElement(function(){d=b.offsetHeight;e=g.offsetHeight;var h=a.getViewport().getSize().height;f=Aa(Math.abs(d),h)},function(){O(b,{overflow:"hidden"})}).then(function(){return qa(b,P(b,{height:R(Q(d,e))}),f).thenAlways(function(){return a.mutateElement(function(){b.hasAttribute("expanded")&&(Y(a,"collapse",b,c),b.removeAttribute("expanded"));O(b,{height:"",overflow:""})})})})}
function Aa(a,b){var c=void 0===c?200:c;var d=void 0===d?500:d;return Math.min(Math.max(Math.abs(a)/b*d,c),d)}S.prototype.K=function(a){Ba(this,a)&&(a.preventDefault(),X(this,a.currentTarget.parentElement,3))};function Ba(a,b){var c=b.target;b=b.currentTarget;var d=!!ja(c,function(f){return"A"==f.tagName},b),e=a.h.hasAction(c,"tap",b);return!d&&!e}
S.prototype.M=function(a){if(!a.defaultPrevented)switch(a.key){case "ArrowUp":case "ArrowDown":var b=this.o.indexOf(a.currentTarget);if(-1!==b){a.preventDefault();a=(b+("ArrowUp"==a.key?-1:1))%this.o.length;0>a&&(a+=this.o.length);try{this.o[a].focus()}catch(c){}}break;case "Enter":case " ":a.target==a.currentTarget&&(a.preventDefault(),X(this,a.currentTarget.parentElement,3))}};
function xa(a,b){b.forEach(function(c){var d=c.target,e=d.hasAttribute("data-expand");d.hasAttribute("expanded")!==e&&X(a,d,2,e)})}S.prototype.S=function(){return this.h};(function(a){a.registerElement("amp-accordion",S,"amp-accordion>section>:last-child{display:none!important}amp-accordion>section[expanded]>:last-child{display:block!important}.i-amphtml-accordion-content,.i-amphtml-accordion-header{margin:0}.i-amphtml-accordion-header{cursor:pointer;background-color:#efefef;padding-right:20px;border:1px solid #dfdfdf}amp-accordion.i-amphtml-display-locking>section:not([expanded])>:last-child,amp-accordion.i-amphtml-display-locking>section:not([expanded])>:last-child *{content-visibility:hidden-matchable!important;display:block!important}amp-accordion>section:not([expanded]) .i-amphtml-media-component,amp-accordion>section:not([expanded]) .i-amphtml-media-component *{display:none!important;visibility:hidden!important}\n/*# sourceURL=/extensions/amp-accordion/0.1/amp-accordion.css*/")})(self.AMP);
})});

//# sourceMappingURL=amp-accordion-0.1.js.map
