(self.AMP=self.AMP||[]).push({n:"amp-mega-menu",v:"2011252111002",f:(function(AMP,_){
'use strict';var k,l="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function m(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}m(this);"function"===typeof Symbol&&Symbol("x");var n;
if("function"==typeof Object.setPrototypeOf)n=Object.setPrototypeOf;else{var p;a:{var q={a:!0},r={};try{r.__proto__=q;p=r.a;break a}catch(a){}p=!1}n=p?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var t=n,u;function v(a){return a?Array.prototype.slice.call(a):[]};var w=self.AMP_CONFIG||{},x=("string"==typeof w.cdnProxyRegex?new RegExp(w.cdnProxyRegex):w.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function y(a){if(self.document&&self.document.head&&(!self.location||!x.test(self.location.origin))){var b=self.document.head.querySelector('meta[name="'+a+'"]');b&&b.getAttribute("content")}}w.cdnUrl||y("runtime-host");w.geoApiUrl||y("amp-geo-api");self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var z=self.__AMP_LOG;function A(){};function B(a){if(a.nodeType){var b=(a.ownerDocument||a).defaultView;b=b.__AMP_TOP||(b.__AMP_TOP=b);a=C(b,"ampdoc").getAmpDoc(a)}return a}function C(a,b){D(a,b);var c=a.__AMP_SERVICES;c||(c=a.__AMP_SERVICES={});a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function D(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)};(function(a){return a||{}})({c:!0,v:!0,a:!0,ad:!0});/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var E;function F(a){try{var b=a.ownerDocument,c=b.createElement("div"),d=b.createElement("div");c.appendChild(d);return c.querySelector(":scope div")===d}catch(g){return!1}};function G(a){var b=a.isConnected;if(void 0!==b)return b;do if(a=H(a),a.host)a=a.host;else break;while(1);return a.nodeType===Node.DOCUMENT_NODE}function H(a){if(Node.prototype.getRootNode)return a.getRootNode()||a;for(;a.parentNode&&(!a||"I-AMPHTML-SHADOW-ROOT"!=a.tagName&&(11!=a.nodeType||"[object ShadowRoot]"!==Object.prototype.toString.call(a)));a=a.parentNode);return a}function I(a,b,c){for(;a&&a!==c;a=a.parentElement)if(b(a))return a;return null}
function J(a){return a.closest?a.closest("header"):I(a,function(b){var c=b.matches||b.webkitMatchesSelector||b.mozMatchesSelector||b.msMatchesSelector||b.oMatchesSelector;return c?c.call(b,"header"):!1})}function K(a,b){a.classList.add("i-amphtml-scoped");var c=b.replace(/^|,/g,"$&.i-amphtml-scoped ");b=a.querySelectorAll(c);a.classList.remove("i-amphtml-scoped");return b}
function L(a,b){if(void 0!==E?E:E=F(a))return a.querySelector(b.replace(/^|,/g,"$&:scope "));var c=K(a,b);return void 0===c[0]?null:c[0]}function M(a){return(void 0!==E?E:E=F(a))?a.querySelectorAll("nav > * > li".replace(/^|,/g,"$&:scope ")):K(a,"nav > * > li")}function N(a){try{a.focus()}catch(b){}};var O=[];function aa(a){var b=[];a=Q(a);for(var c={},d=0;d<a.length;c={j:c.j},d++)c.j=a[d],c.j.parentNode&&v(c.j.parentNode.children).filter(function(g){return function(e){return e!=g.j}}(c)).forEach(function(g){return b.push(g)});return b}function Q(a){for(var b=[],c=a;c;c=c.parentNode||c.host)b.push(c);return b}
function ba(a){for(var b=[];a;){a=H(a);var c=a.querySelectorAll("a[href],area[href],button,details summary,iframe,input,select,textarea,[contenteditable],[draggable],[tabindex]");Array.prototype.push.apply(b,c);a=a.host}return b}
function ca(a){A(O.every(function(f){return f.element!==a}));A(G(a));var b=aa(a),c=Q(a).filter(function(f){return f.nodeType==Node.ELEMENT_NODE}),d=ba(a),g=d.filter(function(f){return a.contains(f)&&void 0!==f.__AMP_MODAL_SAVED_TAB_INDEX}),e=d.filter(function(f){return!a.contains(f)&&void 0===f.__AMP_MODAL_SAVED_TAB_INDEX}),h=b.concat(c).map(function(f){return{element:f,prevValue:f.getAttribute("aria-hidden")}});c.forEach(function(f){return f.removeAttribute("aria-hidden")});b.forEach(function(f){return f.setAttribute("aria-hidden",
"true")});e.forEach(function(f){f.__AMP_MODAL_SAVED_TAB_INDEX=f.getAttribute("tabindex");f.setAttribute("tabindex","-1")});g.forEach(function(f){var P=f.__AMP_MODAL_SAVED_TAB_INDEX;null===P?f.removeAttribute("tabindex"):f.setAttribute("tabindex",P)});O.push({element:a,hiddenElementInfos:h,focusableExternalElements:e,focusableInternalElements:g})}
function da(a){var b=O.pop(),c=b.hiddenElementInfos,d=b.focusableExternalElements;b=b.focusableInternalElements;A(G(a));c.forEach(function(g){var e=g.element,h=g.prevValue;null===h?e.removeAttribute("aria-hidden"):e.setAttribute("aria-hidden",h)});b.forEach(function(g){g.setAttribute("tabindex","-1")});d.forEach(function(g){var e=g.__AMP_MODAL_SAVED_TAB_INDEX;null===e?g.removeAttribute("tabindex"):g.setAttribute("tabindex",e);g.__AMP_MODAL_SAVED_TAB_INDEX=void 0})};function R(a){var b=AMP.BaseElement.call(this,a)||this;b.m=[];b.D=0;b.h=null;b.A=null;b.l=b.win.document;b.o=b.l.documentElement;b.B=null;b.K=a.id||Math.floor(100*Math.random());b.C=b.F.bind(b);b.G=b.I.bind(b);b.H=b.J.bind(b);return b}var S=AMP.BaseElement;R.prototype=l(S.prototype);R.prototype.constructor=R;if(t)t(R,S);else for(var T in S)if("prototype"!=T)if(Object.defineProperties){var U=Object.getOwnPropertyDescriptor(S,T);U&&Object.defineProperty(R,T,U)}else R[T]=S[T];R.L=S.prototype;k=R.prototype;
k.isLayoutSupported=function(a){return"fixed-height"===a};k.prerenderAllowed=function(){return!0};k.buildCallback=function(){var a=B(this.element);a=B(a);a=a.isSingleDoc()?a.win:a;this.B=D(a,"action")?C(a,"action"):null};
k.layoutCallback=function(){this.F();this.element.addEventListener("amp:dom-update",this.C);if(!this.A){var a=this.l.createElement("div");a.classList.add("i-amphtml-mega-menu-mask");a.setAttribute("aria-hidden","true");var b=J(this.element)||this.element;b.classList.add("i-amphtml-mega-menu-mask-parent");b.appendChild(a);this.A=a}u||(u=Promise.resolve(void 0));a=u;return a};k.unlayoutCallback=function(){this.element.removeEventListener("amp:dom-update",this.C);V(this);return!0};
k.F=function(){var a=this;this.m=v(M(this.element));this.m.filter(function(b){return!b.classList.contains("i-amphtml-mega-menu-item")}).forEach(function(b){if(1==b.childElementCount)W(a,b,b.firstElementChild,null);else{var c=L(b,"> button")||L(b,"> [role=button]"),d=L(b,"> [role=dialog]");if(!z.user)throw Error("failed to call initLogConstructor");z.user.assert(c,"amp-mega-menu requires each expandable item to include a button that toggles it.",void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,
void 0);W(a,b,c,d)}})};
function W(a,b,c,d){b.classList.add("i-amphtml-mega-menu-item");a.D++;c.classList.add("i-amphtml-mega-menu-heading");c.hasAttribute("tabindex")||c.setAttribute("tabindex",0);c.addEventListener("click",function(e){return X(a,e)});c.addEventListener("keydown",function(e){if(!e.defaultPrevented)switch(e.key){case "ArrowLeft":case "ArrowRight":var h=a.m.indexOf(e.currentTarget.parentElement);if(-1!==h){e.preventDefault();e="ArrowLeft"==e.key?-1:1;var f=a.l;"rtl"==(f.body.getAttribute("dir")||f.documentElement.getAttribute("dir")||
"ltr")&&(e=-e);h+=e;e=a.m.length;N(Y(a.m[0<h&&0<e?h%e:(h%e+e)%e]))}break;case "Enter":case " ":e.target==e.currentTarget&&X(a,e)}});if(d&&!a.B.hasAction(c,"tap",b)){d.classList.add("i-amphtml-mega-menu-content");d.setAttribute("aria-modal","false");var g=d.getAttribute("id");g||(g=a.K+"_AMP_content_"+a.D,d.setAttribute("id",g));d.insertBefore(Z(a),d.firstChild);d.appendChild(Z(a));c.setAttribute("aria-haspopup","dialog");c.setAttribute("aria-controls",g);c.setAttribute("aria-expanded","false")}}
k.I=function(a){a=a.target;this.h&&!this.h.contains(a)&&G(a)&&V(this)};k.J=function(a){"Escape"===a.key&&V(this)&&a.preventDefault()};function X(a,b){if(ea(a,b)){b.preventDefault();b.stopPropagation();b=b.currentTarget.parentElement;var c=V(a);b!=c&&fa(a,b)}}function ea(a,b){var c=b.target,d=b.currentTarget;return I(c,function(g){return"A"==g.tagName},d)||a.B.hasAction(c,"tap",d)?!1:d.hasAttribute("aria-haspopup")}
function fa(a,b){a.mutateElement(function(){var d=L(b,"> .i-amphtml-mega-menu-content");ca(d);d.setAttribute("aria-modal","true")});b.setAttribute("open","");a.element.setAttribute("open","");a.A.setAttribute("open","");Y(b).setAttribute("aria-expanded","true");var c=b.querySelector(".i-amphtml-screen-reader");N(c);a.o.addEventListener("click",a.G);a.o.addEventListener("keydown",a.H);a.h=b}
function V(a){if(!a.h)return null;var b=a.h;a.mutateElement(function(){var d=L(b,"> .i-amphtml-mega-menu-content");da(d);d.setAttribute("aria-modal","false")});b.removeAttribute("open");a.element.removeAttribute("open");a.A.removeAttribute("open");var c=Y(b);c.setAttribute("aria-expanded","false");b.contains(a.l.activeElement)&&N(c);a.o.removeEventListener("click",a.G);a.o.removeEventListener("keydown",a.H);a.h=null;return b}function Y(a){return L(a,"> .i-amphtml-mega-menu-heading")}
function Z(a){var b=a.element.getAttribute("data-close-button-aria-label")||"Close the menu",c=a.l.createElement("button");c.textContent=b;c.classList.add("i-amphtml-screen-reader");c.addEventListener("click",function(){return V(a)});return c}(function(a){a.registerElement("amp-mega-menu",R,"amp-mega-menu{z-index:1000!important;white-space:nowrap!important}amp-mega-menu.i-amphtml-layout-size-defined[open]{overflow:visible!important}amp-mega-menu nav{background:#fff}amp-mega-menu nav>*{margin:0}amp-mega-menu .i-amphtml-mega-menu-item{display:inline-block!important}amp-mega-menu .i-amphtml-mega-menu-heading{cursor:pointer!important}amp-mega-menu .i-amphtml-mega-menu-content{position:absolute!important;left:0;width:100vw;opacity:0!important;visibility:hidden!important;background:#fff}amp-mega-menu .i-amphtml-mega-menu-item[open]>.i-amphtml-mega-menu-content{visibility:visible!important;opacity:1!important}amp-mega-menu .i-amphtml-mega-menu-item:not([open]) .i-amphtml-screen-reader{display:none!important}.i-amphtml-mega-menu-mask-parent{z-index:1000!important;position:relative}.i-amphtml-mega-menu-mask{position:fixed!important;z-index:-1!important;visibility:hidden!important;opacity:0!important;top:0!important;bottom:0!important;left:0!important;right:0!important;background:rgba(0,0,0,0.5);transition:opacity 200ms,visibility 0s 200ms}.i-amphtml-mega-menu-mask[open]{opacity:1!important;visibility:visible!important;transition:opacity 200ms}\n/*# sourceURL=/extensions/amp-mega-menu/0.1/amp-mega-menu.css*/")})(self.AMP);
})});

//# sourceMappingURL=amp-mega-menu-0.1.js.map
